version: '3'

services:
  app:
    build: .
    container_name: api_backend_preprod
    depends_on:
      - dbpostgres_preprod
    links:
      - dbpostgres_preprod
    volumes:
      -  ./:/home/app/
    expose:
      - 80
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://dbpostgres_preprod:5433/database
      - SPRING_DATASOURCE_USERNAME=username
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - VIRTUAL_PORT=8080
      - VIRTUAL_HOST=api-recipe.preprod.nonstopintegration.ml
      - LETSENCRYPT_HOST=api-recipe.preprod.nonstopintegration.ml
      - LETSENCRYPT_EMAIL=nonstopintegration@gmail.com

  dbpostgres_preprod:
    image: postgres:13.1-alpine
    container_name: dbpostgres_preprod
    volumes:
      - postgres_preprod:/var/lib/postgresql
      - postgres_data_preprod:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - 5433:5433

volumes:
  postgres_data_preprod:
  postgres_preprod:
  app_data:

networks:
  default:
    external:
      name: webproxy