version: '3'

services:
  app_prod:
    build:
      context: .
      args:
        - ENV=prod
    image: backend_prod
    container_name: backend_prod
    depends_on:
      - dbpostgres_prod
    links:
      - dbpostgres_prod
    volumes:
      -  ./:/home/app/
    expose:
      - 80
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://dbpostgres_prod:5432/database
      - SPRING_DATASOURCE_USERNAME=username
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - VIRTUAL_PORT=8080
      - VIRTUAL_HOST=api-recipe.nonstopintegration.ml
      - LETSENCRYPT_HOST=api-recipe.nonstopintegration.ml
      - LETSENCRYPT_EMAIL=nonstopintegration@gmail.com

  dbpostgres_prod:
    image: postgres:13.1-alpine
    container_name: dbpostgres_prod
    volumes:
      - postgres_prod:/var/lib/postgresql
      - postgres_data_prod:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password

volumes:
  postgres_data_prod:
  postgres_prod:

networks:
  default:
    external:
      name: webproxy