version: '3'

services:
  app:
    build: .
    container_name: api_backend_prod
    depends_on:
      - dbpostgres
    links:
      - dbpostgres
    volumes:
      -  ./:/home/app/
    expose:
      - 80
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://dbpostgres:5432/cooking
      - SPRING_DATASOURCE_USERNAME=cooking
      - SPRING_DATASOURCE_PASSWORD=cooking
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - VIRTUAL_PORT=8080
      - VIRTUAL_HOST=api-recipe.nonstopintegration.ml
      - LETSENCRYPT_HOST=api-recipe.nonstopintegration.ml
      - LETSENCRYPT_EMAIL=nonstopintegration@gmail.com

  dbpostgres:
    image: postgres:13.1-alpine
    container_name: dbpostgres
    volumes:
      - postgres:/var/lib/postgresql
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: cooking
      POSTGRES_USER: cooking
      POSTGRES_PASSWORD: cooking
    ports:
      - 5432:5432

volumes:
  postgres_data:
  postgres:
  app_data:

networks:
  default:
    external:
      name: webproxy